Feature/add tagged images to api
codeuniversity/smag-mvp pull request #149
Opened 2019-11-13 15:33 UTC by jo-fr

# Description

This PR adds an API Endpoint to get the posts of a user and an index for the post_tagged_user

Fixes #147 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] Cleanup (changes in structure but not functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2019-11-13 16:11 UTC, 1Jo1 approved these changes

2019-11-13 17:48 UTC, alexmorten requested changes

2019-11-13 17:48 UTC, alexmorten commented on api/grpcserver/grpc_server.go
> +		rows.Scan(&post.Id, &post.PostId, &post.ShortCode, &post.Caption, &post.ImgUrl)
This is not a `post_tagged_users.id`

2019-11-13 17:49 UTC, alexmorten requested changes

2019-11-13 17:49 UTC, alexmorten commented on api/grpcserver/grpc_server.go
> +										ON posts.id=post_tagged_users.post_id
This is missing an index on `post_tagged_users.post_id`

2019-11-16 11:33 UTC, alexmorten requested changes

2019-11-16 11:33 UTC, alexmorten commented on db/migrations/000013_add_index_to_posts_id_ref.up copy.sql
> +CREATE INDEX posts_id_index ON posts (id);
This file has `copy` in its name 😅 
+ I think this should not be necessary on the primary key

2019-11-18 14:17 UTC, alexmorten approved these changes

2019-11-18 14:50 UTC, merged