Feature/add followings
codeuniversity/smag-mvp pull request #62
Opened 2019-10-24 14:05 UTC by jo-fr

# Description

adds following of user to response of `GetUserWithUsername`

Fixes #61 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Cleanup (changes in structure but not functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] run on local machine and test request with `prototool`
- [ ] Test B

**Test Configuration**:
* Go version:
* Kafka version:
* Kubernetes version:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

2019-10-24 17:00 UTC, Urhengulas requested changes

2019-10-24 17:00 UTC, Urhengulas commented on api/grpcserver/main/main.go
> +	s := server.NewGrpcServer(postgresHost, postgresPassword, 10000)
Don't we want to also have an environ-var for the `GRPC_PORT`?
I would give it a default of `1000`, so we don't even need to put it into docker-compose, but it will be easier if we want to change it at some point.

2019-10-24 17:00 UTC, Urhengulas commented on api/grpcserver/grpc_server.go
> +	db, err := sql.Open("postgres", fmt.Sprintf("host=%s user=postgres dbname=instascraper sslmode=disable password=%s", postgresHost, postgresPassword))
Let's also make the `postgresPassword` optional like e.g. https://github.com/codeuniversity/smag-mvp/blob/master/twitter_inserter_posts/inserter.go#L37

2019-10-24 17:00 UTC, Urhengulas commented on api/grpcserver/grpc_server.go
> +	rows, err := s.db.Query("Select follows.to_id as id, users.user_name from follows  join users on follows.to_id=users.id where follows.from_id=$1", u.Id)
Typo
```suggestion
	rows, err := s.db.Query("Select follows.to_id as id, users.user_name from follows join users on follows.to_id=users.id where follows.from_id=$1", u.Id)
```

2019-10-24 17:00 UTC, Urhengulas commented on api/grpcserver/grpc_server.go
> +	if err != nil {
Use `utils.PanicIfNotNil(err)` here?
```suggestion
	utils.PanicIfNotNil(err)
```

2019-10-24 17:00 UTC, Urhengulas commented on api/grpcserver/grpc_server.go
> +	if err != nil {
Use `utils.PanicIfNotNil(err)` here?
```suggestion
	utils.PanicIfNotNil(err)
```

2019-10-24 20:44 UTC, alexmorten commented on api/grpcserver/grpc_server.go
> +	if err != nil {
Why not just return the error?

2019-10-25 09:20 UTC, lukas-menzel approved these changes

2019-10-25 10:22 UTC, m-lukas requested changes

2019-10-25 10:22 UTC, m-lukas commented on api/grpcserver/grpc_server.go
> +	rows, err := s.db.Query("SELECT id, user_name, real_name, bio, avatar_url FROM users WHERE LOWER(user_name) LIKE LOWER($1)", fmt.Sprintf("%%%s%%", username.UserName))
What is `%%%s%%` doing?

2019-10-25 10:22 UTC, m-lukas commented on api/proto/usersearch.pb.go
> +	return 0
Could there be an existing user with `id=0` as well?

2019-10-25 10:24 UTC, m-lukas commented on api/grpcserver/grpc_server.go
> +	rows, err := s.db.Query("SELECT id, user_name, real_name, bio, avatar_url FROM users WHERE LOWER(user_name) LIKE LOWER($1)", fmt.Sprintf("%%%s%%", username.UserName))
Against sql Injection

2019-10-25 10:26 UTC, m-lukas approved these changes

2019-10-25 19:35 UTC, alexmorten reviewed
What do you think about adding what users follow the current user too? :) 
(As in the reverse relation of what you added)

2019-10-25 19:35 UTC, alexmorten commented on api/grpcserver/grpc_server.go
> +		rows.Scan(&u.Id, &u.UserName, &u.RealName, &u.Bio, &u.AvatarUrl)
you can just return the err if `rows.Scan` returns a non nil err (like below)

2019-10-26 11:23 UTC, alexmorten requested changes

2019-10-26 11:23 UTC, alexmorten commented on api/grpcserver/grpc_server.go
> +		err := rows.Scan(&user.Id, &user.UserName)
Here we rely on the query that is passed in knowing that id and user name need to be in this order. 
Can we pass this line in from outside?
That would also make adding fields later simpler

2019-10-26 11:55 UTC, alexmorten approved these changes

2019-10-26 12:00 UTC, Urhengulas approved these changes

2019-10-26 12:05 UTC, merged