Refactor cli to use entrypoint
codeuniversity/smag-mvp pull request #88
Opened 2019-10-30 12:59 UTC by m-lukas

# Description

Refactors cli to use mainly command arguments instead of env variables while leaving `KAFKA_ADDRESS`, `KAFKA_INSTAGRAM_TOPIC` and `KAFKA_TWITTER_TOPIC` for configuration purposes.  Implements the support for command arguments in the docker image.

Fixes #82 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Cleanup (changes in structure but not functionality)

2019-11-03 22:18 UTC, Urhengulas requested changes
Are you going to add a usage example to docker-compose?

2019-11-03 22:20 UTC, Urhengulas requested changes
And it might be useful to add some kind of configurable sleep to be able to directly insert a username at `make run`.

2019-11-04 09:41 UTC, alexmorten commented on cli/Dockerfile
> +CMD [ "" ]
```suggestion
```
you don't need the `CMD`

2019-11-04 15:32 UTC, m-lukas commented
> Are you going to add a usage example to docker-compose?

No because some people might not know that it's executed via docker-compose in the future and therefore it's better to let everyone execute it on its own. However, I added an explanation how to add it to the README to give a hint how to add it.

2019-11-04 16:04 UTC, m-lukas commented
I would just leave the CMD in because while it seems that `alpine` has no default command, it just erases the command if there is one and is already tested.

2019-11-04 16:05 UTC, m-lukas commented on cli/Dockerfile
> +CMD [ "" ]
```suggestion
CMD [ "" ] # optional explicit statement
```

2019-11-04 17:00 UTC, Urhengulas approved these changes

2019-11-04 18:23 UTC, merged